Enhance Post job step with additional echo commands for better status reporting

diff --git a/.github/workflows/MyFirstWorkFlow.yml b/.github/workflows/MyFirstWorkFlow.yml
--- a/.github/workflows/MyFirstWorkFlow.yml
+++ b/.github/workflows/MyFirstWorkFlow.yml
@@ -96,9 +96,17 @@ jobs:
     Post:
         runs-on: ubuntu-latest
         steps:
-            - run: echo "Post"; exit 1
+            - run: echo "Post"; sleep 30; exit 1
+
+            - if: cancelled()
+              run: echo "Canceled!!!"
+
+            - if: failure()
+              run: echo "Failure!!!"
+
             - if: success()
               run: echo "Success!!!"
+            
             - if: always()
               run: echo "Always!!!"
 
